version: "3.8"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - $PWD/checks:/opt/hbland/checkcompare/checks